sudo: required
dist: trusty
language: node_js
node_js:
  - node
addons:
    chrome: stable
before_script:
    - npm run setup
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
    - npm run transpile
    - npm run build

script:
    - npm run test

after_script:
    - npm run format
    - npm pack
